### ISSUE TITLE
Mesh / armature size mismatch

### ISSUE THREAD

**Issue by rbregier** [OliverJPost/HumGen3D#47] opened 2023-02-16 10:50 UTC
Hi,

The batch generator produces meshes which are much smaller than the armature in  2-6 percent of cases (according to my observations). Teeth and eyeballs seem correct however.

Additionally, error messages regularly pop up during the generations, e.g.:
![image](https://user-images.githubusercontent.com/1822210/219344643-3a1342ff-a830-4c57-a53f-7c9bfcd85298.png)
![image](https://user-images.githubusercontent.com/1822210/219344668-448704be-2229-42b1-9c11-07aa32c03ff9.png)
![image](https://user-images.githubusercontent.com/1822210/219344686-7e8881f1-e103-4784-901b-8393aee617a4.png)
![image](https://user-images.githubusercontent.com/1822210/219344696-d3cf9d3f-5e6e-4a8a-b59e-226c424b068b.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1822210/219341444-09494f8c-4870-4892-8827-61a1ad87e82e.png)

Applying a random pose to such a model leads to weird results due to the mesh/armature mismatch:
![image](https://user-images.githubusercontent.com/1822210/219342240-420ff2e7-d4ef-43f2-b32a-acea93d7656f.png)

**To Reproduce**

Run this script multiple times until you get a monster:
```python
import bpy
from HumGen3D.batch_generator.generator import BatchHumanGenerator
from HumGen3D import Human

context = bpy.context

generator = BatchHumanGenerator(add_clothing=False, add_hair=True, add_expression=True)

# Scene cleaning, if needed
bpy.ops.object.select_all(action='DESELECT')
if 'HumGen' in bpy.data.collections.keys():
    while len(bpy.data.collections['HumGen'].objects) > 0:
        obj = bpy.data.collections['HumGen'].objects[0]
        human = Human.from_existing(obj)
        human.delete()
    
human = generator.generate_human(context=context)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Blender Version 3.3.3
 - Human Generator Version 4.0.11

**Comment by OliverJPost** [comment] 2023-02-20 23:49
Very intriguing bug, will look into it. Thanks for the detailed report!
The mentioned error messages are harmless, but I will take care of them

**Comment by OliverJPost** [comment] 2023-02-25 22:42
It seems like it's caused by a faulty expression, most likely "talking". I've created #60 for this. In the next beta update where we update the Base_Humans pack this will be fixed

**Closed by OliverJPost** 2023-02-25 22:42 UTC
Labels: bug
